import { Dimensions, Platform } from 'react-native';

import { CountryCodeType } from 'modules/auth/types';

export const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
export const isAndroid = Platform.OS === 'android';
export const isIOS = Platform.OS === 'ios';

export const COUNTRIES: CountryCodeType[] = [
  {
    countryName: 'United States',
    countryCode: 'US',
    countryPhoneCode: '+1',
    countrySource: 'https://flagcdn.com/us.svg',
  },
  {
    countryName: 'Canada',
    countryCode: 'CA',
    countryPhoneCode: '+1',
    countrySource: 'https://flagcdn.com/ca.svg',
  },
  {
    countryName: 'United Kingdom',
    countryCode: 'GB',
    countryPhoneCode: '+44',
    countrySource: 'https://flagcdn.com/gb.svg',
  },
  {
    countryName: 'Germany',
    countryCode: 'DE',
    countryPhoneCode: '+49',
    countrySource: 'https://flagcdn.com/de.svg',
  },
  {
    countryName: 'France',
    countryCode: 'FR',
    countryPhoneCode: '+33',
    countrySource: 'https://flagcdn.com/fr.svg',
  },
  {
    countryName: 'Italy',
    countryCode: 'IT',
    countryPhoneCode: '+39',
    countrySource: 'https://flagcdn.com/it.svg',
  },
  {
    countryName: 'Spain',
    countryCode: 'ES',
    countryPhoneCode: '+34',
    countrySource: 'https://flagcdn.com/es.svg',
  },
  {
    countryName: 'Australia',
    countryCode: 'AU',
    countryPhoneCode: '+61',
    countrySource: 'https://flagcdn.com/au.svg',
  },
  {
    countryName: 'Japan',
    countryCode: 'JP',
    countryPhoneCode: '+81',
    countrySource: 'https://flagcdn.com/jp.svg',
  },
  {
    countryName: 'China',
    countryCode: 'CN',
    countryPhoneCode: '+86',
    countrySource: 'https://flagcdn.com/cn.svg',
  },
  {
    countryName: 'India',
    countryCode: 'IN',
    countryPhoneCode: '+91',
    countrySource: 'https://flagcdn.com/in.svg',
  },
  {
    countryName: 'Brazil',
    countryCode: 'BR',
    countryPhoneCode: '+55',
    countrySource: 'https://flagcdn.com/br.svg',
  },
  {
    countryName: 'Russia',
    countryCode: 'RU',
    countryPhoneCode: '+7',
    countrySource: 'https://flagcdn.com/ru.svg',
  },
  {
    countryName: 'Mexico',
    countryCode: 'MX',
    countryPhoneCode: '+52',
    countrySource: 'https://flagcdn.com/mx.svg',
  },
  {
    countryName: 'South Africa',
    countryCode: 'ZA',
    countryPhoneCode: '+27',
    countrySource: 'https://flagcdn.com/za.svg',
  },
  {
    countryName: 'South Korea',
    countryCode: 'KR',
    countryPhoneCode: '+82',
    countrySource: 'https://flagcdn.com/kr.svg',
  },
  {
    countryName: 'Saudi Arabia',
    countryCode: 'SA',
    countryPhoneCode: '+966',
    countrySource: 'https://flagcdn.com/sa.svg',
  },
  {
    countryName: 'Argentina',
    countryCode: 'AR',
    countryPhoneCode: '+54',
    countrySource: 'https://flagcdn.com/ar.svg',
  },
  {
    countryName: 'Turkey',
    countryCode: 'TR',
    countryPhoneCode: '+90',
    countrySource: 'https://flagcdn.com/tr.svg',
  },
  {
    countryName: 'Netherlands',
    countryCode: 'NL',
    countryPhoneCode: '+31',
    countrySource: 'https://flagcdn.com/nl.svg',
  },
  {
    countryName: 'Switzerland',
    countryCode: 'CH',
    countryPhoneCode: '+41',
    countrySource: 'https://flagcdn.com/ch.svg',
  },
  {
    countryName: 'Sweden',
    countryCode: 'SE',
    countryPhoneCode: '+46',
    countrySource: 'https://flagcdn.com/se.svg',
  },
  {
    countryName: 'Norway',
    countryCode: 'NO',
    countryPhoneCode: '+47',
    countrySource: 'https://flagcdn.com/no.svg',
  },
  {
    countryName: 'Denmark',
    countryCode: 'DK',
    countryPhoneCode: '+45',
    countrySource: 'https://flagcdn.com/dk.svg',
  },
  {
    countryName: 'Finland',
    countryCode: 'FI',
    countryPhoneCode: '+358',
    countrySource: 'https://flagcdn.com/fi.svg',
  },
  {
    countryName: 'Belgium',
    countryCode: 'BE',
    countryPhoneCode: '+32',
    countrySource: 'https://flagcdn.com/be.svg',
  },
  {
    countryName: 'Austria',
    countryCode: 'AT',
    countryPhoneCode: '+43',
    countrySource: 'https://flagcdn.com/at.svg',
  },
  {
    countryName: 'Ireland',
    countryCode: 'IE',
    countryPhoneCode: '+353',
    countrySource: 'https://flagcdn.com/ie.svg',
  },
  {
    countryName: 'New Zealand',
    countryCode: 'NZ',
    countryPhoneCode: '+64',
    countrySource: 'https://flagcdn.com/nz.svg',
  },
  {
    countryName: 'Poland',
    countryCode: 'PL',
    countryPhoneCode: '+48',
    countrySource: 'https://flagcdn.com/pl.svg',
  },
  {
    countryName: 'Czech Republic',
    countryCode: 'CZ',
    countryPhoneCode: '+420',
    countrySource: 'https://flagcdn.com/cz.svg',
  },
  {
    countryName: 'Portugal',
    countryCode: 'PT',
    countryPhoneCode: '+351',
    countrySource: 'https://flagcdn.com/pt.svg',
  },
  {
    countryName: 'Greece',
    countryCode: 'GR',
    countryPhoneCode: '+30',
    countrySource: 'https://flagcdn.com/gr.svg',
  },
  {
    countryName: 'Hungary',
    countryCode: 'HU',
    countryPhoneCode: '+36',
    countrySource: 'https://flagcdn.com/hu.svg',
  },
  {
    countryName: 'Romania',
    countryCode: 'RO',
    countryPhoneCode: '+40',
    countrySource: 'https://flagcdn.com/ro.svg',
  },
  {
    countryName: 'Israel',
    countryCode: 'IL',
    countryPhoneCode: '+972',
    countrySource: 'https://flagcdn.com/il.svg',
  },
  {
    countryName: 'United Arab Emirates',
    countryCode: 'AE',
    countryPhoneCode: '+971',
    countrySource: 'https://flagcdn.com/ae.svg',
  },
  {
    countryName: 'Singapore',
    countryCode: 'SG',
    countryPhoneCode: '+65',
    countrySource: 'https://flagcdn.com/sg.svg',
  },
  {
    countryName: 'Malaysia',
    countryCode: 'MY',
    countryPhoneCode: '+60',
    countrySource: 'https://flagcdn.com/my.svg',
  },
  {
    countryName: 'Thailand',
    countryCode: 'TH',
    countryPhoneCode: '+66',
    countrySource: 'https://flagcdn.com/th.svg',
  },
  {
    countryName: 'Indonesia',
    countryCode: 'ID',
    countryPhoneCode: '+62',
    countrySource: 'https://flagcdn.com/id.svg',
  },
  {
    countryName: 'Philippines',
    countryCode: 'PH',
    countryPhoneCode: '+63',
    countrySource: 'https://flagcdn.com/ph.svg',
  },
  {
    countryName: 'Vietnam',
    countryCode: 'VN',

    countryPhoneCode: '+84',
    countrySource: 'https://flagcdn.com/vn.svg',
  },
  {
    countryName: 'Pakistan',
    countryCode: 'PK',
    countryPhoneCode: '+92',
    countrySource: 'https://flagcdn.com/pk.svg',
  },
  {
    countryName: 'Bangladesh',
    countryCode: 'BD',
    countryPhoneCode: '+880',
    countrySource: 'https://flagcdn.com/bd.svg',
  },
  {
    countryName: 'Egypt',
    countryCode: 'EG',
    countryPhoneCode: '+20',
    countrySource: 'https://flagcdn.com/eg.svg',
  },
  {
    countryName: 'Nigeria',
    countryCode: 'NG',
    countryPhoneCode: '+234',
    countrySource: 'https://flagcdn.com/ng.svg',
  },
  {
    countryName: 'Kenya',
    countryCode: 'KE',
    countryPhoneCode: '+254',
    countrySource: 'https://flagcdn.com/ke.svg',
  },
  {
    countryName: 'Ethiopia',
    countryCode: 'ET',
    countryPhoneCode: '+251',
    countrySource: 'https://flagcdn.com/et.svg',
  },
  {
    countryName: 'Morocco',
    countryCode: 'MA',
    countryPhoneCode: '+212',
    countrySource: 'https://flagcdn.com/ma.svg',
  },
  {
    countryName: 'Ghana',
    countryCode: 'GH',
    countryPhoneCode: '+233',
    countrySource: 'https://flagcdn.com/gh.svg',
  },
  {
    countryName: 'Ivory Coast',
    countryCode: 'CI',
    countryPhoneCode: '+225',
    countrySource: 'https://flagcdn.com/ci.svg',
  },
  {
    countryName: 'Tanzania',
    countryCode: 'TZ',
    countryPhoneCode: '+255',
    countrySource: 'https://flagcdn.com/tz.svg',
  },
  {
    countryName: 'Uganda',
    countryCode: 'UG',
    countryPhoneCode: '+256',
    countrySource: 'https://flagcdn.com/ug.svg',
  },
  {
    countryName: 'Algeria',
    countryCode: 'DZ',
    countryPhoneCode: '+213',
    countrySource: 'https://flagcdn.com/dz.svg',
  },
  {
    countryName: 'Tunisia',
    countryCode: 'TN',
    countryPhoneCode: '+216',
    countrySource: 'https://flagcdn.com/tn.svg',
  },
  {
    countryName: 'Libya',
    countryCode: 'LY',
    countryPhoneCode: '+218',
    countrySource: 'https://flagcdn.com/ly.svg',
  },
  {
    countryName: 'Sudan',
    countryCode: 'SD',
    countryPhoneCode: '+249',
    countrySource: 'https://flagcdn.com/sd.svg',
  },
  {
    countryName: 'Chile',
    countryCode: 'CL',
    countryPhoneCode: '+56',
    countrySource: 'https://flagcdn.com/cl.svg',
  },
  {
    countryName: 'Colombia',
    countryCode: 'CO',
    countryPhoneCode: '+57',
    countrySource: 'https://flagcdn.com/co.svg',
  },
  {
    countryName: 'Peru',
    countryCode: 'PE',
    countryPhoneCode: '+51',
    countrySource: 'https://flagcdn.com/pe.svg',
  },
  {
    countryName: 'Venezuela',
    countryCode: 'VE',
    countryPhoneCode: '+58',
    countrySource: 'https://flagcdn.com/ve.svg',
  },
  {
    countryName: 'Bolivia',
    countryCode: 'BO',
    countryPhoneCode: '+591',
    countrySource: 'https://flagcdn.com/bo.svg',
  },
  {
    countryName: 'Paraguay',
    countryCode: 'PY',
    countryPhoneCode: '+595',
    countrySource: 'https://flagcdn.com/py.svg',
  },
  {
    countryName: 'Uruguay',
    countryCode: 'UY',
    countryPhoneCode: '+598',
    countrySource: 'https://flagcdn.com/uy.svg',
  },
  {
    countryName: 'Costa Rica',
    countryCode: 'CR',
    countryPhoneCode: '+506',
    countrySource: 'https://flagcdn.com/cr.svg',
  },
  {
    countryName: 'Panama',
    countryCode: 'PA',
    countryPhoneCode: '+507',
    countrySource: 'https://flagcdn.com/pa.svg',
  },
  {
    countryName: 'Guatemala',
    countryCode: 'GT',
    countryPhoneCode: '+502',
    countrySource: 'https://flagcdn.com/gt.svg',
  },
  {
    countryName: 'Honduras',
    countryCode: 'HN',
    countryPhoneCode: '+504',
    countrySource: 'https://flagcdn.com/hn.svg',
  },
  {
    countryName: 'El Salvador',
    countryCode: 'SV',
    countryPhoneCode: '+503',
    countrySource: 'https://flagcdn.com/sv.svg',
  },
  {
    countryName: 'Cuba',
    countryCode: 'CU',
    countryPhoneCode: '+53',
    countrySource: 'https://flagcdn.com/cu.svg',
  },
  {
    countryName: 'Haiti',
    countryCode: 'HT',
    countryPhoneCode: '+509',
    countrySource: 'https://flagcdn.com/ht.svg',
  },
  {
    countryName: 'Jamaica',
    countryCode: 'JM',
    countryPhoneCode: '+1876',
    countrySource: 'https://flagcdn.com/jm.svg',
  },
  {
    countryName: 'Dominican Republic',
    countryCode: 'DO',
    countryPhoneCode: '+1809',
    countrySource: 'https://flagcdn.com/do.svg',
  },
  {
    countryName: 'Puerto Rico',
    countryCode: 'PR',
    countryPhoneCode: '+1787',
    countrySource: 'https://flagcdn.com/pr.svg',
  },
  {
    countryName: 'Trinidad and Tobago',
    countryCode: 'TT',
    countryPhoneCode: '+1868',
    countrySource: 'https://flagcdn.com/tt.svg',
  },
  {
    countryName: 'Barbados',
    countryCode: 'BB',
    countryPhoneCode: '+1246',
    countrySource: 'https://flagcdn.com/bb.svg',
  },
  {
    countryName: 'Bahamas',
    countryCode: 'BS',
    countryPhoneCode: '+1242',
    countrySource: 'https://flagcdn.com/bs.svg',
  },
  {
    countryName: 'Guyana',
    countryCode: 'GY',
    countryPhoneCode: '+592',
    countrySource: 'https://flagcdn.com/gy.svg',
  },
  {
    countryName: 'Suriname',
    countryCode: 'SR',
    countryPhoneCode: '+597',
    countrySource: 'https://flagcdn.com/sr.svg',
  },
  {
    countryName: 'Fiji',
    countryCode: 'FJ',
    countryPhoneCode: '+679',
    countrySource: 'https://flagcdn.com/fj.svg',
  },
  {
    countryName: 'Papua New Guinea',
    countryCode: 'PG',
    countryPhoneCode: '+675',
    countrySource: 'https://flagcdn.com/pg.svg',
  },
  {
    countryName: 'Samoa',
    countryCode: 'WS',
    countryPhoneCode: '+685',
    countrySource: 'https://flagcdn.com/ws.svg',
  },
  {
    countryName: 'Tonga',
    countryCode: 'TO',
    countryPhoneCode: '+676',
    countrySource: 'https://flagcdn.com/to.svg',
  },
  {
    countryName: 'Solomon Islands',
    countryCode: 'SB',
    countryPhoneCode: '+677',
    countrySource: 'https://flagcdn.com/sb.svg',
  },
  {
    countryName: 'Vanuatu',
    countryCode: 'VU',
    countryPhoneCode: '+678',
    countrySource: 'https://flagcdn.com/vu.svg',
  },
  {
    countryName: 'Tuvalu',
    countryCode: 'TV',
    countryPhoneCode: '+688',
    countrySource: 'https://flagcdn.com/tv.svg',
  },
  {
    countryName: 'Kiribati',
    countryCode: 'KI',
    countryPhoneCode: '+686',
    countrySource: 'https://flagcdn.com/ki.svg',
  },
  {
    countryName: 'Marshall Islands',
    countryCode: 'MH',
    countryPhoneCode: '+692',
    countrySource: 'https://flagcdn.com/mh.svg',
  },
  {
    countryName: 'Palau',
    countryCode: 'PW',
    countryPhoneCode: '+680',
    countrySource: 'https://flagcdn.com/pw.svg',
  },
  {
    countryName: 'Micronesia',
    countryCode: 'FM',
    countryPhoneCode: '+691',
    countrySource: 'https://flagcdn.com/fm.svg',
  },
];
